### ISSUE TITLE
'expected one argument' when passing a negative coordinates value

### ISSUE THREAD

**Issue by spatialhast** [gumblex/tms2geotiff#1]
'expected one argument' error when passing a negative coordinates value:
```
python3 tms2geotiff.py -s https://b.tile.opentopomap.org/{z}/{x}/{y}.png -f -12.47,130.96 -t -12.49,130.98 -z 6 output.tiff
usage: tms2geotiff.py [-h] [-s URL] [-f LAT,LON] [-t LAT,LON] [-z ZOOM] output
tms2geotiff.py: error: argument -f/--from: expected one argument
```

**Comment by gumblex** [comment]
Try `--from=-12.47,130.96 --to=-12.49,130.98`

**Comment by tli47** [comment]
I met a issue when download a large area(earth range  -180 -90.0 180 90) with the GUI tool. The "math domain error" occured.

Do you have any idea? @gumblex 

<img width="281" alt="cf39c414a2801f32e18e0ad46053bdf" src="https://github.com/gumblex/tms2geotiff/assets/26863079/50ae6025-1486-404f-be33-ad6e9da1a663">


<img width="190" alt="fa1c2e5ec44e8434218af8bfcef5d82" src="https://github.com/gumblex/tms2geotiff/assets/26863079/5dd8a595-7fd2-49e3-a7bb-21cfa1f00335">
