### ISSUE TITLE
Add BigTIFF support for images larger than 4GB

### ISSUE THREAD

**Issue by gtnbssn** [gumblex/tms2geotiff#3]
Tiff images cannot be larger than 4GB, this will cause the script to crash when trying to create a large GeoTIFF.

From what I found online a solution would be to use tifffile, but it would still require numpy.

To solve my issue, I instead made use of the gdal part already present in your script. Here are my changes:

```diff
diff --git a/tms2geotiff.py b/tms2geotiff.py
index e5508d1..787d61d 100644
--- a/tms2geotiff.py
+++ b/tms2geotiff.py
@@ -271,7 +271,7 @@ def save_image(img, filename, matrix, **params):
     return img
 
 
-def save_geotiff_gdal(img, filename, matrix):
+def save_geotiff_gdal(img, filename, matrix, big):
     if 'GDAL_DATA' in os.environ:
         del os.environ['GDAL_DATA']
     if 'PROJ_LIB' in os.environ:
@@ -283,9 +283,13 @@ def save_geotiff_gdal(img, filename, matrix):
 
     imgbands = len(img.getbands())
     driver = gdal.GetDriverByName('GTiff')
+    gtiffOptions=['COMPRESS=DEFLATE', 'PREDICTOR=2', 'NUM_THREADS=8', 'ZLEVEL=9', 'TILED=YES']
+    if big:
+        gtiffOptions.append('BIGTIFF=YES')
     gtiff = driver.Create(filename, img.size[0], img.size[1],
         imgbands, gdal.GDT_Byte,
-        options=['COMPRESS=DEFLATE', 'PREDICTOR=2', 'ZLEVEL=9', 'TILED=YES'])
+        options=gtiffOptions)
     gtiff.SetGeoTransform(matrix)
     gtiff.SetProjection(WKT_3857)
     for band in range(imgbands):
@@ -297,10 +301,10 @@ def save_geotiff_gdal(img, filename, matrix):
     return img
 
 
-def save_image_auto(img, filename, matrix, use_gdal=False, **params):
+def save_image_auto(img, filename, matrix, big=False, **params):
     ext = os.path.splitext(filename)[1].lower()
-    if ext in ('.tif', '.tiff') and use_gdal:
-        return save_geotiff_gdal(img, filename, matrix)
+    if ext in ('.tif', '.tiff') and big:
+        return save_geotiff_gdal(img, filename, matrix, big)
     else:
         return save_image(img, filename, matrix, **params)
 
@@ -465,6 +469,7 @@ def main():
         help="extent in one string (use either -e, or -f and -t)")
     parser.add_argument("-z", "--zoom", type=int, help="zoom level")
     parser.add_argument("-g", "--gui", action='store_true', help="show GUI")
+    parser.add_argument("-B", "--big", action='store_true', help="create a BigTIFF image (uses GDAL)")
     parser.add_argument("output", nargs='?', help="output file")
     args = parser.parse_args()
     if args.gui or not all(getattr(args, opt, None) for opt in
@@ -488,7 +493,7 @@ def main():
     download_args.append(print_progress)
 
     img, matrix = download_extent(*download_args)
-    save_image_auto(img, args.output, matrix)
+    save_image_auto(img, args.output, matrix, args.big)
     return 0
```

This allowed me to create TIFF files of 12GB and above. This requires GDAL and numpy.

Note that I also changed 'NUM_THREADS' from '1' to '8'. Otherwise the compression on a single core is extremely long. Downloading and creating a 13GB GeoTIFF took slightly more than 1 hour on my M2.

I don't know if there are any drawbacks to using BigTIFF even when the file is small.

Thanks for the tool! Have you considered [tqdm](https://github.com/tqdm/tqdm) for reporting on the progress of the download? It might make things easier/cleaner.

**Comment by gumblex** [comment]
I want to try using the tifffile library instead of GDAL because it requires many dependencies. I will keep the GDAL function though.

For the progress reporting, you can patch the `print_progress` function.

Can you provide your coordinates and zoom of your big image for testing?
I also want to know the max memory and time (excluding download time) requirement of writing your 13GB image, using your current patch.

**Comment by gtnbssn** [comment]
The TMS service I am using isn't public, but you should be able to test using mapzen terrain for instance: https://gis.stackexchange.com/questions/201831/how-to-efficiently-access-files-with-gdal-from-an-s3-bucket-using-vsis3/202608#202608

I didn't time precisely the 13GB file creation, it was more than one hour and the download was by very far the quickest part (maybe 10 minutes). In my first attempts I had kept NUM_THREADS to 1 and it was way too long.

My laptop has 32 GB of ram, it was entirely used and used swap as well. Looking at the python process in MacOS activity monitor it was using up to 67GB of ram.

**Comment by gumblex** [comment]
This is now supported.
