### ISSUE TITLE
How to disable the GUI when running "python3 tms2geotiff.py"?

### ISSUE THREAD

**Issue by DevByDay0628** [gumblex/tms2geotiff#4]
Running 'python3 tms2geotiff.py' by default will open the GUI. How to disable the GUI when running "python3 tms2geotiff.py"?

**Comment by gumblex** [comment]
If you want to see help, run: `python3 tms2geotiff.py --help`
If you want to download images, run it with url and coordinates.
If you really want to disable the gui, remove [line 654](https://github.com/gumblex/tms2geotiff/blob/323369d9404505bb881ee96d383a30adc14687ff/tms2geotiff.py#L654)
